platform :ios, '7.0'

inhibit_all_warnings!

def share
	  pod 'Rexxar', :git => 'https://github.com/xujialiang/rexxar-ios.git', :commit => 'master'
	  pod 'YYKit'
      pod 'ReactiveCocoa', '~> 2.5'
end


target 'CredooHybridFramework' do
	share
end

target 'Sample' do
	share
end
